### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by yaozeizei** [ds4owd-001/md-02-assignments-Yaozeizei#1]
@larnsce @mianzg @sskorik01

First of all, thank you!

I have two questions. 1) For task 10, the x-axis label seems to be all squished together, will we be learning about how to make adjustments to the labels? 2) This is sort of related, I was using the geom_col() on my own data, and I was trying to change the order of the categories on the x-axis, I had to manually change the order by numbering the categories, but is there another way to do it? Lastly, it's kind of embarrassing but I couldn't find where to delete a code chunk. 

Thanks!

Zeyu

**Comment by larnsce** [comment]
Thank you for your great questions, @yaozeizei.

> 1) For task 10, the x-axis label seems to be all squished together, will we be learning about how to make adjustments to the labels?

To format the x-axis labels in ggplot2 to show "10k" instead of "10000", you can use the `scales` package in R. The `scales` package provides a function called `label_number()` which can be used to format the labels on the axes. This function allows you to specify a suffix (like "k" for thousands) and a scale factor to adjust the magnitude of the numbers.

```r
library(ggplot2)
library(scales)

ggplot(data = gapminder_2007,
       mapping = aes(x = gdpPercap,
                     y = lifeExp,
                     size = pop,
                     color = country)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~continent) +
  scale_x_continuous(labels = label_number(suffix = "k", scale = 1e-3))
```
In the `label_number()` function, `suffix = "k"` adds the "k" suffix to the labels, and `scale = 1e-3` scales the numbers down by a factor of 1000 (since 1e-3 is equivalent to 1/1000). This will result in numbers like "10000" being displayed as "10k" on the x-axis.

From: https://www.perplexity.ai/search/In-ggplot2-use-..AswX_ASIKxugnkKANexg?s=c

> 2) This is sort of related, I was using the geom_col() on my own data, and I was trying to change the order of the categories on the x-axis, I had to manually change the order by numbering the categories, but is there another way to do it?

You learn how to this using factors (fct). Any column in your data that's categorical is currently stored as character (chr). We can add levels which denote the order we want by turning the column into a factor. This is also applicable to homework assignment 3.

Example with our sanitation data from Module 3 (md-03-exercises):

```
sanitation <- read_csv("data/jmp_wld_sanitation_long.csv")

levels_varname_long <- c("safely managed sanitation services", 
                         "basic sanitation services", 
                         "limited sanitation services", 
                         "unimproved sanitation facilities", 
                         "no sanitation facilities")

sanitation |> 
  mutate(varname_long = factor(varname_long, levels = levels_varname_long))
```

> Lastly, it's kind of embarrassing but I couldn't find where to delete a code chunk.

Every questions is a good question. It's a bit challenging to delete a code chunk in Visual editing mode, I have also encountered that problem. When you hit the delete key on your keyboard, also delete the `{r}` that starts the code chunk, once that's entirely deleted the code chunk should disappear.
